name: ci
on:
  push:
    branches:
      - '*'
  pull_request:

env:
  GO_VERSION: "1.20"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
      - run: make test
